name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake clang-format python3-pip
          pip install pre-commit
      - name: pre-commit
        run: pre-commit run --files $(git ls-files '*.hpp' '*.cpp')
      - name: Configure
        run: cmake -B build -S .
      - name: Build
        run: cmake --build build
      - name: Test
        run: ctest --test-dir build --output-on-failure
